import { blackSecondary, blackTertiary, greyBg, whitePrimary, whiteSecondary } from 'styles/colours'
import { material } from 'react-native-typography'
import { SQUARE_FRAME_MARGIN, SQUARE_FRAME_DIMENSION, SQUARE_FRAME_PADDING, SQUARE_FRAME_CHIN } from './constants'

export default {
  content: {
    backgroundColor: greyBg,
    flex: 1,
    flexDirection: 'column',
  },
  paper: {
    marginTop: SQUARE_FRAME_MARGIN,
    marginRight: SQUARE_FRAME_MARGIN,
    marginLeft: SQUARE_FRAME_MARGIN,
    paddingTop: SQUARE_FRAME_PADDING,
    paddingRight: SQUARE_FRAME_PADDING,
    paddingBottom: SQUARE_FRAME_PADDING + SQUARE_FRAME_CHIN,
    paddingLeft: SQUARE_FRAME_PADDING,
    backgroundColor: whitePrimary,
    shadowColor: blackTertiary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 2,
    flex: 0,
    alignSelf: 'center',
  },
  print: {
    position: 'relative',
    alignSelf: 'center',
    width: SQUARE_FRAME_DIMENSION + 1,
    height: SQUARE_FRAME_DIMENSION + 1,
    borderWidth: 1,
    borderColor: whitePrimary,
    overflow: 'hidden',
  },
  iconBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 40,
    flex: 1,
    maxHeight: 100,
    alignItems: 'flex-start',
  },
  buttonContainer: {
    padding: 10,
    alignSelf: 'center',
  },
  iconExpand: {
    color: blackSecondary,
    padding: 10,
    marginBottom: 4,
    alignSelf: 'center',
    fontSize: 30,
  },
  iconRotate: {
    color: blackSecondary,
    fontSize: 30,
    marginTop: -7,
  },
  borderBox: {
    opacity: 0,
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 2,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
  },
  gridOverlay: {
    opacity: 0,
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 3,
  },
  gridBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(250,250,250,0.3)',
    margin: -0.5,
  },
  gridBlack: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
  },
  pixelScore: {
    opacity: 0,
    flex: 1,
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: (SQUARE_FRAME_CHIN / 2) - 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pixelScoreDimensions: {
    ...material.captionObject,
    color: whiteSecondary,
    fontSize: 18,
    lineHeight: 18,
    marginVertical: 7,
  },
  pixelScoreTitle: {
    ...material.captionObject,
    color: whiteSecondary,
    fontSize: 15,
  },
  remoteImageLoading: {
    position: 'absolute',
    backgroundColor: '#E2E2E2',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
}
