fastlane_version '2.97.0'

platform :ios do

  # iOS Lanes

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'com.wundershine.app', type: 'development', readonly: true)
    match(app_identifier: 'com.wundershine.app', type: 'appstore', readonly: true)
    match(app_identifier: 'com.wundershine.app.ShareReceiver', type: 'development', readonly: true)
    match(app_identifier: 'com.wundershine.app.ShareReceiver', type: 'appstore', readonly: true)
  end

  desc 'Build the iOS application'
  lane :build do
    certificates
    # increment_build_number(xcodeproj: './ios/Wundershine.xcodeproj')
    gym(
      scheme: 'Wundershine',
      workspace: './ios/Wundershine.xcworkspace'
    )
  end

  desc 'Ship to Testflight'
  lane :beta do
    build
    pilot
    commit_version_bump(message: 'Version bump', xcodeproj: './ios/Wundershine.xcodeproj')
    push_to_git_remote
  end

end

platform :android do

  # Android Lanes

end